version: '2'

services:

  reverseproxy:
     image: reverseproxy
     ports:
       - 80:80
       - 1403:1433
     restart: on-failure
     networks:
       - my-new-network
     depends_on:
       - ctf-app

  ctf-app:
     image: bnweaver/learning-repo:ctfapp
     container_name: ctf-app_1
     build:
       context: ./Fall2019
     depends_on:
       - ctf-db
       #- reverseproxy
     restart: on-failure
     networks: 
       - my-new-network
     volumes:
       - /var/opt/tmp:/var/opt/tmp

  
  ctf-db:
     image: bnweaver/ctf-repository:ctfdb
     container_name: ctf-db_1
     build:
       context: ./SqlContainer
     restart: on-failure
     environment:
       MSSQL_SA_PASSWORD: SaintLeo123
     networks: 
       - my-new-network

networks:
   my-new-network:
