version: '2'

services:

  #used for session storage
  redisserver:
     image: redis
     container_name: cache
     ports:
       - 6379:6379
     restart: unless-stopped
     networks:
       - my-new-network

  #used for connecting containers to host network
  reverseproxy:
     image: reverseproxy
     container_name: reverseproxy_1
     ports:
       - 80:80
       - 1403:1433
     restart: unless-stopped
     networks:
       - my-new-network
     depends_on:
       - ctf-app
       - ctf-server

  #the web app
  ctf-app:
     container_name: ctf-app
     build:
       context: ./WebApp
     depends_on:
       - ctf-db
       - redisserver
     restart: unless-stopped
     networks: 
       - my-new-network
     volumes:
       - /ctfdata:/ctfdata
     environment:
       - REDIS_URL=redis://cache
       - FILE_PATH=/ctfdata/

  #the http server for files
  ctf-server:
      container_name: ctf-server
      build:
        context: ./WebServer
      restart: unless-stopped
      networks:
        - my-new-network
      volumes:
        - /ctfdata:/ctfdata
      environment:
       - FILE_PATH=/ctfdata/

  #the database
  ctf-db:
     container_name: ctf-db_1
     build:
       context: ./SqlContainer
     restart: unless-stopped
     environment:
       MSSQL_SA_PASSWORD: SaintLeo123
     networks: 
       - my-new-network

#default bridge network so containers can talk to each other
networks:
   my-new-network:
